resources:
  - ../../../base/server

namespace: production

patches:
  - target:
      kind: Deployment
      name: wemeetatplace-server
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
