apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wemeetatplace-prometheus-data
  labels:
    app: wemeetatplace-prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
