apiVersion: v1
kind: Service
metadata:
  name: wemeetatplace-prometheus
  labels:
    app: wemeetatplace-prometheus
spec:
  selector:
    app: wemeetatplace-prometheus
  ports:
    - name: web
      port: 9090
      targetPort: web