apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wemeetatplace-grafana-data
  labels:
    app: wemeetatplace-grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi