apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wemeetatplace
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "10"
    nginx.ingress.kubernetes.io/limit-rpm: "300"
    nginx.ingress.kubernetes.io/limit-connections: "20"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "5"
spec:
  ingressClassName: nginx
  rules:
    - host: staging.wemeetatplace.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wemeetatplace-server
                port:
                  number: 80
