resources:
  - ../server
  - ../user
  - ../../../base/ingress

namespace: staging
patches:
  - target:
      kind: Ingress
      name: wemeetatplace
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: staging.wemeetatplace.local
