apiVersion: apps/v1
kind: Deployment
metadata:
  name: wemeetatplace-server
  labels:
    app: wemeetatplace-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wemeetatplace-server
  template:
    metadata:
      labels:
        app: wemeetatplace-server
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80