apiVersion: apps/v1
kind: Deployment
metadata:
  name: wemeetatplace-server
  labels:
    app: wemeetatplace-server
spec:
  selector:
    matchLabels:
      app: wemeetatplace-server
  template:
    metadata:
      labels:
        app: wemeetatplace-server
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: server
          image: ghcr.io/nett/wemeetatplace-server:latest
          env:
            - name: APPLICATION_NAME
              value: WeMeetAt.Place
          ports:
            - containerPort: 3000
