resources:
- ../../../base/server

namespace: staging

images:
- name: ghcr.io/nett/wemeetatplace-server
  newTag: 4bc8d0b

patches:
- path: deployment-patch.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
