resources:
  - ../../../base/user

namespace: staging

patches:
  - target:
      kind: Deployment
      name: wemeetatplace-user
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
