resources:
  - ../../../base/auth

namespace: staging

patches:
  - target:
      kind: Deployment
      name: wemeetatplace-auth
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
