name: Cleanup old images

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup server images
        uses: snok/container-retention-policy@v3.0.1
        with:
          account: user
          image-names: "wemeetatplace-server"
          cut-off: 2d
          keep-n-most-recent: 3
          dry-run: false
          token: ${{ secrets.WEMEETATPLACE_APP }}

      - name: Cleanup user images
        uses: snok/container-retention-policy@v3.0.1
        with:
          account: user
          image-names: "wemeetatplace-user"
          cut-off: 2d
          keep-n-most-recent: 3
          dry-run: false
          token: ${{ secrets.WEMEETATPLACE_APP }}